{
"themes": [
{ "theme": "Funny Cat Mom", "productType": "Digital Clipart", "style": "Bold Typography", "status": "Pending" },
{ "theme": "Boho Wildflower Bundle", "productType": "Digital Clipart", "style": "Watercolor", "status": "Pending" },
{ "theme": "Hiking Mountain Sunset", "productType": "Wall Art Print", "style": "Retro/Vintage", "status": "Pending" },
{ "theme": "Cottagecore Frog Friends", "productType": "Digital Clipart", "style": "Illustrated", "status": "Pending" },
{ "theme": "Dark Academia Books", "productType": "Digital Clipart", "style": "Line Art", "status": "Pending" },
{ "theme": "Nurse Life Hero", "productType": "Digital Clipart", "style": "Bold Typography", "status": "Pending" },
{ "theme": "Coquette Pink Bows", "productType": "Digital Clipart", "style": "Maximalist", "status": "Pending" },
{ "theme": "Mushroom Forest Magic", "productType": "Printable Poster", "style": "Cottagecore", "status": "Pending" },
{ "theme": "Minimalist Botanical Leaves", "productType": "Wall Art Print", "style": "Minimalist", "status": "Pending" },
{ "theme": "Halloween Spooky Ghosts", "productType": "Digital Clipart", "style": "Illustrated", "status": "Pending" },
{ "theme": "Celestial Moon Stars", "productType": "Digital Clipart", "style": "Boho/Watercolor", "status": "Pending" },
{ "theme": "Coffee Addict Morning", "productType": "Digital Clipart", "style": "Bold Typography", "status": "Pending" },
{ "theme": "Tarot Card Aesthetic", "productType": "Printable Poster", "style": "Dark/Gothic", "status": "Pending" },
{ "theme": "Western Cowgirl Boots", "productType": "Digital Clipart", "style": "Retro/Vintage", "status": "Pending" },
{ "theme": "Plant Mom Jungle", "productType": "Digital Clipart", "style": "Watercolor", "status": "Pending" },
{ "theme": "Yoga Lotus Wellness", "productType": "Wall Art Print", "style": "Minimalist", "status": "Pending" },
{ "theme": "Vintage Floral Wreath", "productType": "Digital Clipart", "style": "Retro/Vintage", "status": "Pending" },
{ "theme": "Goblincore Mushroom Snail", "productType": "Digital Clipart", "style": "Illustrated", "status": "Pending" },
{ "theme": "Ocean Wave Watercolor", "productType": "Wall Art Print", "style": "Watercolor", "status": "Pending" },
{ "theme": "Butterfly Garden Spring", "productType": "Digital Clipart", "style": "Watercolor", "status": "Pending" },
{ "theme": "Galaxy Space Planet", "productType": "Wall Art Print", "style": "Abstract", "status": "Pending" },
{ "theme": "Birthday Queen Crown", "productType": "Digital Clipart", "style": "Maximalist", "status": "Pending" },
{ "theme": "Fox Woodland Autumn", "productType": "Printable Poster", "style": "Illustrated", "status": "Pending" },
{ "theme": "Autumn Leaves Harvest", "productType": "Digital Clipart", "style": "Watercolor", "status": "Pending" },
{ "theme": "Tropical Parrot Paradise", "productType": "Wall Art Print", "style": "Watercolor", "status": "Pending" },
{ "theme": "Dachshund Wiener Dog", "productType": "Digital Clipart", "style": "Illustrated", "status": "Pending" },
{ "theme": "Easter Spring Bunny", "productType": "Digital Clipart", "style": "Illustrated", "status": "Pending" },
{ "theme": "Abstract Geometric Shapes", "productType": "Wall Art Print", "style": "Abstract", "status": "Pending" },
{ "theme": "Skeleton Halloween Spooky", "productType": "Digital Clipart", "style": "Dark/Gothic", "status": "Pending" },
{ "theme": "Japanese Zen Minimal", "productType": "Wall Art Print", "style": "Minimalist", "status": "Pending" },
{ "theme": "Crystal Healing Spiritual", "productType": "Digital Clipart", "style": "Boho/Watercolor", "status": "Pending" },
{ "theme": "Galentines Day Girls", "productType": "Digital Clipart", "style": "Maximalist", "status": "Pending" },
{ "theme": "Mental Health Warrior", "productType": "Digital Clipart", "style": "Bold Typography", "status": "Pending" },
{ "theme": "Witchy Autumn Moon", "productType": "Digital Clipart", "style": "Dark/Gothic", "status": "Pending" },
{ "theme": "Sunflower Summer Bright", "productType": "Wall Art Print", "style": "Watercolor", "status": "Pending" },
{ "theme": "Boho Rainbow Arch", "productType": "Digital Clipart", "style": "Boho/Watercolor", "status": "Pending" },
{ "theme": "Cherry Blossom Japan", "productType": "Digital Clipart", "style": "Watercolor", "status": "Pending" },
{ "theme": "Succulent Cactus Desert", "productType": "Digital Clipart", "style": "Illustrated", "status": "Pending" },
{ "theme": "Panda Bear Cute", "productType": "Digital Clipart", "style": "Illustrated", "status": "Pending" },
{ "theme": "Hummingbird Flower", "productType": "Digital Clipart", "style": "Watercolor", "status": "Pending" },
{ "theme": "Budget Planner Finance", "productType": "Printable Planner", "style": "Minimalist", "status": "Pending" },
{ "theme": "Weekly Schedule Planner", "productType": "Printable Planner", "style": "Minimalist", "status": "Pending" },
{ "theme": "Habit Tracker 30 Day", "productType": "Printable Planner", "style": "Minimalist", "status": "Pending" },
{ "theme": "Vision Board Template", "productType": "Printable Planner", "style": "Maximalist", "status": "Pending" },
{ "theme": "Baby Shower Games Bundle", "productType": "Printable Card", "style": "Illustrated", "status": "Pending" },
{ "theme": "Wedding Table Numbers", "productType": "Printable Card", "style": "Minimalist", "status": "Pending" },
{ "theme": "Christmas Gift Tags", "productType": "Printable Card", "style": "Retro/Vintage", "status": "Pending" },
{ "theme": "Rose Garden Romantic", "productType": "Digital Clipart", "style": "Watercolor", "status": "Pending" },
{ "theme": "Flamingo Tropical Pink", "productType": "Wall Art Print", "style": "Maximalist", "status": "Pending" },
{ "theme": "Axolotl Kawaii Water", "productType": "Digital Clipart", "style": "Illustrated", "status": "Pending" }
],
"sales": []
}